FROM python:3.13-slim

WORKDIR /booking_app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо код програми
COPY app ./app
# Копіюємо тести
COPY tests ./tests

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Вказуємо новий правильний шлях до папки з тестами
CMD ["pytest", "-v", "tests/"]